version: "3.6"

services:

  grafana:
    #    build:
    #  context: ./grafana
    #  dockerfile: Dockerfile
    image: grafana:latest
    container_name: grafana
    networks:
      - grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=hadesarchitect-cassandra-datasource
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
      - GF_AUTH_ANONYMOUS_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000/api/health && echo 'ready'"]
      interval: 10s
      retries: 30


networks:
  grafana:
    name: grafana
    driver: bridge

